#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sh $HOME/.local/bin/lemonbar/run_lemonbar.sh &
libinput-gestures -c $XDG_CONFIG_HOME/libinput-gestures/libinput-gestures.bspwm.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Nemo state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Zathura state=tiled
